name: Test

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*

jobs:
  test:
    name: Test ${{ matrix.os }} ${{ matrix.triplet }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            triplet: x86-windows
            install_script: .github/scripts/install-windows.sh
            build_script: .github/scripts/build-windows.sh
          - os: ubuntu-18.04
            triplet: x64-linux
            install_script: .github/scripts/install-ubuntu.sh
            build_script: .github/scripts/build-ubuntu.sh
          - os: macos-latest
            triplet: x64-osx
            install_script: .github/scripts/install-macos.sh
            build_script: .github/scripts/build-macos.sh debug
          - os: macos-11.0
            triplet: arm64-osx
            install_script: .github/scripts/install-macos.sh silicon
            build_script: .github/scripts/build-macos.sh debug silicon
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install & Build
        shell: bash
        run: |
          ${{ matrix.install_script }}
          ${{ matrix.build_script }}